export enum SocketEventEnum {
  boardsJoin = 'boards:join',
  boardsLeave = 'boards:leave',
  boardsUpdate = 'boards:update',
  boardsUpdateSucess = 'boards:updateSucess',
  boardsUpdateFailure = 'boards:updateFailure',
  boardsDelete = 'boards:delete',
  boardsDeleteSucess = 'boards:deleteSucess',
  boardsDeleteFailure = 'boards:deleteFailure',

  columnsDelete = 'columns:delete',
  columnsDeleteSucess = 'columns:deleteSucess',
  columnsDeleteFailure = 'boards:deleteFailure',
  columnsCreate = 'columns:create',
  columnsCreateSucess = 'columns:createSucess',
  columnsCreateFailure = 'columns:createFailure',
  columnsUpdate = 'columns:update',
  columnsUpdateSucess = 'columns:updateSucess',
  columnsUpdateFailure = 'columns:updateFailure',
  tasksCreate = 'tasks:create',
  tasksCreateSucess = 'tasks:createSucess',
  tasksCreateFailure = 'tasks:createFailure',
  tasksUpdate = 'tasks:update',
  tasksUpdateSucess = 'tasks:updateSucess',
  tasksUpdateFailure = 'tasks:updateFailure',
  tasksDelete = 'tasks:delete',
  tasksDeleteSucess = 'tasks:deleteSucess',
  tasksDeleteFailure = 'tasks:deleteFailure'
}
